services:
  client:
    build: 
      dockerfile: Dockerfile
      context: ./client
    container_name: client
    restart: always
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./client:/client
      - /client/node_modules
    ports:
      - 5173:5173
    depends_on:
      - server
  
  
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    container_name: server
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db
    env_file: ./server/.env
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db
    env_file:
      - ./server/.env
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro

volumes:
  db-data: