services:
  server:
    build:
      context: .
    restart: always
    environment:
      NODE_ENV: production
      DB_HOST: db
    env_file: ".env"
    ports:
      - 3000:3000
    depends_on:
      - db
  
  db:
    container_name: postgres-db
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql:ro

volumes:
  db-data: